### ISSUE TITLE
scons 2.2.0 leaves some of the inner classes out bin/syncronizer.jar

### ISSUE THREAD

**Issue by patrick-higgins** [planestraveler/git-starteam#36]
Building with scons 2.2.0 on Fedora 18 yields a syncronizer.jar that is missing these three classes:

org/ossnoize/git/fastimport/FileModification$1.class
org/sync/githelper/GitHelper$1.class
org/sync/util/LogEntry$1.class

**Comment by planestraveler** [comment]
Scons was dropped for some time. Fully using ant script for the build now.
